export const FILMS_LIST_SHOW = 'FILMS_LIST_SHOW';
export const ACTIVE_TAB_FILMS = 'ACTIVE_TAB_FILMS';
export const ACTIVE_TAB_BOOKMARKS = 'ACTIVE_TAB_BOOKMARKS';
export const CHECK_FILM = 'CHECK_FILM';
export const SEARCH_FILTER = 'SEARCH_FILTER';
export const GET_FILMS_LIST = 'GET_FILMS_LIST';




