export const ACTIVE_TAB_FILMS = 'ACTIVE_TAB_FILMS';
export const ACTIVE_TAB_BOOKMARKS = 'ACTIVE_TAB_BOOKMARKS';
export const CHECK_FILM = 'CHECK_FILM';
export const SEARCH_FILTER = 'SEARCH_FILTER';
export const GET_FILMS_LIST = 'GET_FILMS_LIST';
export const TAG_FILTER = 'TAG_FILTER';
export const TAG_DELETE = 'TAG_DELETE';




