export const FILMS_LIST_SHOW = 'FILMS_LIST_SHOW';
export const ACTIVE_TAB_FILMS = 'ACTIVE_TAB_FILMS';
export const ACTIVE_TAB_BOOKMARKS = 'ACTIVE_TAB_BOOKMARKS';
export const ADD_TO_BOOKMARKS = 'ADD_TO_BOOKMARKS';
export const REMOVE_FROM_BOOKMARKS = 'REMOVE_FROM_BOOKMARKS';
export const CHECK_FILM = 'CHECK_FILM';




